#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Exact finite audit for GAMMA-DELTA AX v0.1."""

from __future__ import annotations

from fractions import Fraction
from collections import defaultdict
import math


def entropy(ps):
    out=0.0
    for p in ps:
        if p:
            out -= float(p)*math.log2(float(p))
    return out


def mi_from_joint(joint):
    px=defaultdict(Fraction)
    py=defaultdict(Fraction)
    total=sum(joint.values(),Fraction(0))
    assert total==1
    for (x,y),p in joint.items():
        px[x]+=p;py[y]+=p
    out=0.0
    for (x,y),p in joint.items():
        if not p: continue
        r=Fraction(p,1)/(px[x]*py[y])
        out += float(p)*math.log2(float(r))
    return out


def binary_channel_mi(qp, channel):
    # qp: P(P=0),P(P=1)
    joint=defaultdict(Fraction)
    for p,wp in enumerate(qp):
        for y,wy in channel[p].items():
            joint[(p,y)] += wp*wy
    return mi_from_joint(joint)


def delta_cap(qp,channel):
    support=sum(1 for p in qp if p)
    if support<=1:
        return 0.0
    return binary_channel_mi(qp,channel)/math.log2(support)


def delta_dec(qp,channel):
    h=entropy(qp)
    if h==0:
        return float("nan")
    return binary_channel_mi(qp,channel)/h


def gamma_arith(x,y): return (x+y)/2
def gamma_geom(x,y): return math.sqrt(x*y)
def gamma_min(x,y): return min(x,y)

def gamma_balance(x,y):
    if x+y==0: return float("nan")
    return 2*min(x,y)/(x+y)


def assert_close(a,b,eps=1e-12):
    if abs(a-b)>eps:
        raise AssertionError((a,b))


def main():
    print("=== GAMMA–DELTA AX v0.1 ===")

    # ---------- Gamma semantic branch ----------
    one_way=(1.0,0.0)
    balanced=(0.5,0.5)
    no_flow=(0.0,0.0)
    full=(1.0,1.0)

    print("\n[GAMMA] aggregators")
    for name,f in [
        ("arith",gamma_arith),
        ("geom",gamma_geom),
        ("min",gamma_min),
    ]:
        print(name,
              "F(1,0)=",f(*one_way),
              "F(.5,.5)=",f(*balanced),
              "F(1,1)=",f(*full))
        assert_close(f(*balanced),0.5)
        assert_close(f(*no_flow),0.0)
        assert_close(f(*full),1.0)

    assert_close(gamma_arith(*one_way),0.5)
    assert_close(gamma_geom(*one_way),0.0)
    assert_close(gamma_min(*one_way),0.0)
    assert_close(gamma_arith(*balanced),0.5)
    assert_close(gamma_balance(*one_way),0.0)
    assert_close(gamma_balance(*balanced),1.0)

    print("G-WEAK current arithmetic: PASS")
    print("G-STRONG current arithmetic: FAIL-EXACT")
    print("G0-G5 uniqueness: REFUTED by arith/geom/min")
    print("same Gamma, different directional balance: PASS")

    # ---------- Delta decomposition ----------
    perfect={
        0:{0:Fraction(1),1:Fraction(0)},
        1:{0:Fraction(0),1:Fraction(1)},
    }
    independent={
        0:{0:Fraction(1,2),1:Fraction(1,2)},
        1:{0:Fraction(1,2),1:Fraction(1,2)},
    }
    noisy={
        0:{0:Fraction(3,4),1:Fraction(1,4)},
        1:{0:Fraction(1,4),1:Fraction(3,4)},
    }

    qu=(Fraction(1,2),Fraction(1,2))
    qn=(Fraction(3,4),Fraction(1,4))

    dc_u=delta_cap(qu,perfect)
    dd_u=delta_dec(qu,perfect)
    dc_n=delta_cap(qn,perfect)
    dd_n=delta_dec(qn,perfect)
    kappa=entropy(qn)/1.0

    print("\n[DELTA]")
    print("uniform perfect: cap=",dc_u,"dec=",dd_u)
    print("nonuniform perfect: cap=",dc_n,"dec=",dd_n,"kappa=",kappa)
    print("independent uniform: cap=",delta_cap(qu,independent))
    print("noisy uniform: cap=",delta_cap(qu,noisy))

    assert_close(dc_u,1.0)
    assert_close(dd_u,1.0)
    assert_close(dd_n,1.0)
    assert_close(dc_n,kappa)
    assert dc_n < 1.0
    assert_close(delta_cap(qu,independent),0.0)

    # exact factorization numerically on two channels/q
    for q,ch in [(qu,noisy),(qn,noisy),(qn,perfect)]:
        h=entropy(q)
        lhs=delta_cap(q,ch)
        rhs=(h/math.log2(sum(1 for p in q if p))) * delta_dec(q,ch)
        assert_close(lhs,rhs)
    print("Delta = kappa_q * delta_dec: PASS")
    print("D-CAP vs D-DEC nonuniform perfect-decoding distinction: PASS")

    # ---------- Independence witnesses ----------
    # Unified abstract contexts: Gamma directional strengths are generated by
    # exact binary perfect/no-flow kernels; Delta channel is independent module.
    C1={"name":"C1","gamma_xy":(1.0,1.0),"q":qu,"ch":perfect}
    C2={"name":"C2","gamma_xy":(1.0,1.0),"q":qu,"ch":independent}
    C3={"name":"C3","gamma_xy":(1.0,1.0),"q":qu,"ch":perfect}
    C4={"name":"C4","gamma_xy":(1.0,0.0),"q":qu,"ch":perfect}

    def G(C): return gamma_arith(*C["gamma_xy"])
    def D(C): return delta_cap(C["q"],C["ch"])

    assert_close(G(C1),G(C2))
    assert abs(D(C1)-D(C2))>1e-12
    assert_close(D(C3),D(C4))
    assert abs(G(C3)-G(C4))>1e-12

    print("\n[INDEPENDENCE]")
    print("IND-1:",
          "Gamma",G(C1),"=",G(C2),
          "Delta",D(C1),"!=",D(C2))
    print("IND-2:",
          "Delta",D(C3),"=",D(C4),
          "Gamma",G(C3),"!=",G(C4))
    print("Gamma->Delta functional dependence: REFUTED on finite domain")
    print("Delta->Gamma functional dependence: REFUTED on finite domain")

    print("\n=== VERDICT ===")
    print("GAMMA: AX-NONUNIQUE + SEMANTIC-BRANCH(G-WEAK)")
    print("DELTA: EXACT-DECOMPOSITION(D-CAP = kappa_q * D-DEC)")
    print("GAMMA/DELTA: INDEPENDENCE-WITNESS")
    return 0


if __name__=="__main__":
    raise SystemExit(main())
